[0m12:57:28.504609 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1808B9BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1827E4C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1827E4F70>]}


============================== 12:57:28.507610 | bd9f7543-52eb-406d-ba9e-d10fdba4c974 ==============================
[0m12:57:28.507610 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:57:28.508611 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:57:51.090579 [debug] [MainThread]: Starter project path: c:\Users\dmitry.v\Documents\dbt\dbt_workshop\.venv\lib\site-packages\dbt\include\starter_project
[0m12:57:51.102579 [info ] [MainThread]:
Your new dbt project "dbtworkshop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:57:51.103580 [info ] [MainThread]: Setting up your profile.
[0m12:57:59.521478 [debug] [MainThread]: Command `dbt init` succeeded at 12:57:59.521478 after 31.07 seconds
[0m12:57:59.521478 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1808B9BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1827E4F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F18284EF40>]}
[0m12:57:59.522482 [debug] [MainThread]: Flushing usage events
[0m12:58:00.128620 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:01:07.780388 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231B87E0D60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231BA719670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231BA719460>]}


============================== 13:01:07.783388 | ad57629f-fab8-4639-b0ce-b121d5fa3bed ==============================
[0m13:01:07.783388 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:01:07.784388 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:01:17.034074 [info ] [MainThread]: A project called dbtworkshop already exists here.
[0m13:01:17.036072 [debug] [MainThread]: Command `dbt init` succeeded at 13:01:17.035073 after 9.31 seconds
[0m13:01:17.036072 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231B87E0D60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231BA719400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000231BA6D4820>]}
[0m13:01:17.037072 [debug] [MainThread]: Flushing usage events
[0m13:01:17.658194 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:02:02.927967 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027D43B0FD30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027D45A48640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027D45A48430>]}


============================== 13:02:02.930967 | 90b2e0a0-fed4-4b11-8e61-9044c2eb5ff6 ==============================
[0m13:02:02.930967 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:02:02.931968 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt clean', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:02:02.931968 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\dmitry.v\Documents\dbt\dbt_workshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m13:02:02.932969 [debug] [MainThread]: Command `dbt clean` failed at 13:02:02.932969 after 0.06 seconds
[0m13:02:02.933968 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027D43B0FD30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027D45A48CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027D45A48D00>]}
[0m13:02:02.933968 [debug] [MainThread]: Flushing usage events
[0m13:02:03.562004 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:02:16.042396 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019C8E43FD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019C903796A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019C90379490>]}


============================== 13:02:16.045397 | 300308e0-541b-49da-8311-3271e7f6e272 ==============================
[0m13:02:16.045397 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:02:16.046397 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:02:22.636816 [info ] [MainThread]: A project called dbtworkshop already exists here.
[0m13:02:22.637816 [debug] [MainThread]: Command `dbt init` succeeded at 13:02:22.637816 after 6.65 seconds
[0m13:02:22.638816 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019C8E43FD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019C90379430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019C90334790>]}
[0m13:02:22.638816 [debug] [MainThread]: Flushing usage events
[0m13:02:23.171458 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:02:46.235699 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E316680D60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E3185B9670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E3185B9460>]}


============================== 13:02:46.238699 | a1552a2f-7a3a-4910-98b4-997827a33598 ==============================
[0m13:02:46.238699 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:02:46.239699 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:02:49.158433 [debug] [MainThread]: Starter project path: C:\Users\dmitry.v\Documents\dbt\dbt_workshop\.venv\lib\site-packages\dbt\include\starter_project
[0m13:02:49.197434 [info ] [MainThread]:
Your new dbt project "dbtworkshop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:02:49.198435 [info ] [MainThread]: Setting up your profile.
[0m13:03:25.272602 [info ] [MainThread]: Profile dbtworkshop written to C:\Users\dmitry.v\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:03:25.273601 [debug] [MainThread]: Command `dbt init` succeeded at 13:03:25.273601 after 39.09 seconds
[0m13:03:25.274602 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E316680D60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E3185B9400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E318574AF0>]}
[0m13:03:25.274602 [debug] [MainThread]: Flushing usage events
[0m13:03:25.844287 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:03:43.972963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F9705FD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F98F986A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F98F98490>]}


============================== 13:03:43.975963 | 5772020b-3423-4f66-a2db-62fd37673631 ==============================
[0m13:03:43.975963 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:03:43.976963 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:03:43.989964 [info ] [MainThread]: dbt version: 1.9.2
[0m13:03:43.990965 [info ] [MainThread]: python version: 3.9.13
[0m13:03:43.991965 [info ] [MainThread]: python path: C:\Users\dmitry.v\Documents\dbt\dbt_workshop\.venv\scripts\python.exe
[0m13:03:43.991965 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m13:03:44.040969 [info ] [MainThread]: Using profiles dir at C:\Users\dmitry.v\.dbt
[0m13:03:44.040969 [info ] [MainThread]: Using profiles.yml file at C:\Users\dmitry.v\.dbt\profiles.yml
[0m13:03:44.041969 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\dmitry.v\Documents\dbt\dbt_workshop\dbt_project.yml
[0m13:03:44.042966 [info ] [MainThread]: adapter type: postgres
[0m13:03:44.042966 [info ] [MainThread]: adapter version: 1.9.0
[0m13:03:44.043966 [info ] [MainThread]: Configuration:
[0m13:03:44.043966 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m13:03:44.044965 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:03:44.044965 [info ] [MainThread]: Required dependencies:
[0m13:03:44.044965 [debug] [MainThread]: Executing "git --help"
[0m13:03:44.070967 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:03:44.071967 [debug] [MainThread]: STDERR: "b''"
[0m13:03:44.071967 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:03:44.072967 [info ] [MainThread]: Connection:
[0m13:03:44.073969 [info ] [MainThread]:   host: localhost
[0m13:03:44.073969 [info ] [MainThread]:   port: 5432
[0m13:03:44.074970 [info ] [MainThread]:   user: postgres
[0m13:03:44.074970 [info ] [MainThread]:   database: postgres
[0m13:03:44.074970 [info ] [MainThread]:   schema: dev
[0m13:03:44.075968 [info ] [MainThread]:   connect_timeout: 10
[0m13:03:44.075968 [info ] [MainThread]:   role: None
[0m13:03:44.076968 [info ] [MainThread]:   search_path: None
[0m13:03:44.076968 [info ] [MainThread]:   keepalives_idle: 0
[0m13:03:44.077969 [info ] [MainThread]:   sslmode: None
[0m13:03:44.077969 [info ] [MainThread]:   sslcert: None
[0m13:03:44.078969 [info ] [MainThread]:   sslkey: None
[0m13:03:44.078969 [info ] [MainThread]:   sslrootcert: None
[0m13:03:44.079968 [info ] [MainThread]:   application_name: dbt
[0m13:03:44.079968 [info ] [MainThread]:   retries: 1
[0m13:03:44.080969 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m13:03:44.226973 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m13:03:45.688959 [debug] [MainThread]: Using postgres connection "debug"
[0m13:03:45.689959 [debug] [MainThread]: On debug: select 1 as id
[0m13:03:45.689959 [debug] [MainThread]: Opening a new connection, currently in state init
[0m13:03:45.826964 [debug] [MainThread]: SQL status: SELECT 1 in 0.136 seconds
[0m13:03:45.827967 [debug] [MainThread]: On debug: Close
[0m13:03:45.827967 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m13:03:45.828964 [info ] [MainThread]: [31m1 check failed:[0m
[0m13:03:45.828964 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\dmitry.v\Documents\dbt\dbt_workshop\dbt_project.yml> not found

[0m13:03:45.829965 [debug] [MainThread]: Command `dbt debug` failed at 13:03:45.829965 after 1.92 seconds
[0m13:03:45.829965 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m13:03:45.830965 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F9705FD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F9643C400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F9643C4C0>]}
[0m13:03:45.830965 [debug] [MainThread]: Flushing usage events
[0m13:03:46.360743 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:12:49.736619 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000168D6162D60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000168D80AF790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000168D80AF580>]}


============================== 17:12:49.740620 | dfa8128a-2345-476f-8d4a-6f43c149cb68 ==============================
[0m17:12:49.740620 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:12:49.741619 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run --select tag:staging', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:12:49.741619 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\dmitry.v\Documents\dbt\dbt_workshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m17:12:49.743619 [debug] [MainThread]: Command `dbt run` failed at 17:12:49.742619 after 0.06 seconds
[0m17:12:49.743619 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000168D6162D60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000168D80AF520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000168D80AF640>]}
[0m17:12:49.744620 [debug] [MainThread]: Flushing usage events
[0m17:12:50.393849 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:13:24.129570 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000208FC870E20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000208FE7AE790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000208FE7AE9A0>]}


============================== 17:13:24.132571 | 2d33e661-bab9-4f2c-8cde-7bf80f36e9f9 ==============================
[0m17:13:24.132571 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:13:24.133570 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select tag:staging', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:13:24.134571 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\dmitry.v\Documents\dbt\dbt_workshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m17:13:24.135571 [debug] [MainThread]: Command `dbt run` failed at 17:13:24.134571 after 0.06 seconds
[0m17:13:24.135571 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000208FC870E20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000208FE7AE9A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000208FE7AE6D0>]}
[0m17:13:24.135571 [debug] [MainThread]: Flushing usage events
[0m17:13:24.666800 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:15:13.061507 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D245300DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D24723E7C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D24723E9D0>]}


============================== 17:15:13.064507 | 9bb2aed0-7d40-499b-9a11-db7947fe2f9e ==============================
[0m17:15:13.064507 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:15:13.065507 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --select tag:staging', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:15:13.065507 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\dmitry.v\Documents\dbt\dbt_workshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m17:15:13.066508 [debug] [MainThread]: Command `dbt run` failed at 17:15:13.066508 after 0.06 seconds
[0m17:15:13.067507 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D245300DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D24723EA30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D24723E910>]}
[0m17:15:13.067507 [debug] [MainThread]: Flushing usage events
[0m17:15:13.704430 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:15:31.959959 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001249FE5FDF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000124A1D9E6A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000124A1D9E490>]}


============================== 17:15:31.962959 | 970faa3c-ad9f-440e-9e5f-f970d06bd21f ==============================
[0m17:15:31.962959 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:15:31.962959 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:15:31.963960 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\dmitry.v\Documents\dbt\dbt_workshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m17:15:31.964960 [debug] [MainThread]: Command `dbt deps` failed at 17:15:31.964960 after 0.06 seconds
[0m17:15:31.965960 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001249FE5FDF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000124A1D9EA30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000124A1D9ED00>]}
[0m17:15:31.965960 [debug] [MainThread]: Flushing usage events
[0m17:15:32.492110 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:02:33.965739 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A5F1FDC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A7E5E670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A7E5E460>]}


============================== 11:02:33.968739 | be74f225-df9e-4a40-b63f-77b17312e8bb ==============================
[0m11:02:33.968739 [info ] [MainThread]: Running with dbt=1.9.2
[0m11:02:33.969740 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\dmitry.v\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m11:02:33.969740 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\dmitry.v\Documents\dbt\dbt_workshop\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m11:02:33.971741 [debug] [MainThread]: Command `dbt deps` failed at 11:02:33.971741 after 0.06 seconds
[0m11:02:33.971741 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A5F1FDC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A7E5EA00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000285A7E5ECD0>]}
[0m11:02:33.972741 [debug] [MainThread]: Flushing usage events
[0m11:02:34.513738 [debug] [MainThread]: An error was encountered while trying to flush usage events
